name: cabin_booking
description: An app for booking cabins.
version: 0.1.0

author: albertms10
repository: https://github.com/albertms10/cabin_booking.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  cupertino_icons: ^1.0.1+1
  path_provider: ^1.6.24
  provider: ^4.3.2+2
  timer_builder: ^1.3.0
  uuid: ^2.2.2

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
