name: cabin_booking
description: An app for booking cabins.
version: 0.3.0

author: albertms10
repository: https://github.com/albertms10/cabin_booking.git

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.1+1
  flutter_sticky_header: ^0.5.0
  intl: ^0.17.0-nullsafety.2
  path_provider: ^1.6.24
  provider: ^5.0.0-nullsafety.1
  timer_builder: ^1.3.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3

flutter:
  generate: true
  uses-material-design: true
