name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      
      - run: flutter pub get
      
      - name: Analyze project source
        run: dart analyze --fatal-infos
      
      # - run: flutter test
