name: Flutter Desktop (macOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter config --enable-macos-desktop
      - run: flutter pub get

      # - run: flutter test
      - run: flutter build web
