name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter analyze --fatal-infos
    # - run: flutter test


  ios-build:
    name: iOS build
    runs-on: macos-latest
    needs: [analyze]
    if: ${{ false }}

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: dev

    - run: flutter pub get
    - run: flutter build ios --release --no-codesign

    - uses: actions/upload-artifact@v1
      with:
        name: ios_release
        path: build/ios/iphoneos/Runner.app


  android-build:
    name: Android build
    runs-on: ubuntu-latest
    needs: [analyze]
    if: ${{ false }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: android_release
          path: build/app/outputs/flutter-apk/app-release.apk


  macos-build:
    name: macOS build
    runs-on: macos-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos

      - name: 'Tar app'
        run: cd build/macos/Build/Products/Release/ && tar -cvf macos_release.tar "Cabin Booking.app"

      - uses: actions/upload-artifact@v1
        with:
          name: macos_release
          path: build/macos/Build/Products/Release/macos_release.tar


  windows-build:
    name: Windows build
    runs-on: windows-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows

      - name: 'Tar app'
        run: cd build/windows/runner/ && tar -cvf windows_release.tar Release

      - uses: actions/upload-artifact@v1
        with:
          name: windows_release
          path: build/windows/runner/windows_release.tar


  web-build:
    name: Web build
    runs-on: ubuntu-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web

      - name: 'Tar app'
        run: cd build/ && tar -cvf web_release.tar web/

      - uses: actions/upload-artifact@v1
        with:
          name: web_release
          path: build/web_release.tar
