name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze:
    name: Analyze Flutter code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter analyze --fatal-infos
      # - run: flutter test

  ios-build:
    name: Build iOS
    runs-on: macos-latest
    needs: [analyze]

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: dev

    - run: flutter pub get
    - run: flutter build ios --release --no-codesign

  android-build:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter pub get
      - run: flutter build apk

  macos-build:
    name: Build macOS
    runs-on: macos-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos

  windows-build:
    name: Build Windows
    runs-on: windows-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows
  
  web-build:
    name: Build Web
    runs-on: ubuntu-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web
